OnlineShoppingStore/OnlineShoppingStore.WebUI/Controllers/CartController.cs
using OnlineShoppingStore.Domain.Abstract;
using OnlineShoppingStore.Domain.Entities;
using OnlineShoppingStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IProductRepository repo,IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }
        public ViewResult  Index(Cart cart, string returnUrl)
        {
           // return View(new CartIndexViewModel {Cart=GetCart(),ReturnUrl=returnUrl });
            return View(new CartIndexViewModel { Cart = cart, ReturnUrl = returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        //public ViewResult Checkout()
        //{
        //    return View(new ShippingDetails());
        //}
        [HttpGet]
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
       [HttpPost]
        public ViewResult  Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count()==0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessorOrder(cart, shippingDetails);
                cart.clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
            
        }
        public RedirectToRouteResult AddToCart(Cart cart,int productId,string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product!=null)
            {
               // GetCart().AddItem(product, 1);
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl});
        }
        public RedirectToRouteResult RemoveFromCart(Cart cart,int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product!=null)
            {
                //GetCart().RemoveItem(product);
                cart.RemoveItem(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        //private Cart GetCart()
        //{
        //    Cart cart = (Cart)Session["Cart"];
        //    if (cart==null)
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //}
    }
    
}

OnlineShoppingStore/OnlineShoppingStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingStore.Domain.Abstract;

namespace OnlineShoppingStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        // GET: Nav
        //public ActionResult Index()
        //{
        //    return View();
        //}
        private IProductRepository repository;
        public NavController(IProductRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string category=null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products.Select(x => x.Category).Distinct().OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

OnlineShoppingStore/OnlineShoppingStore.WebUI/Controllers/ProductController.cs
using OnlineShoppingStore.Domain.Abstract;
using OnlineShoppingStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        //public ActionResult Index()
        //{
        //    return View();
        //}
        private readonly IProductRepository repository;
        public int PageSize=4; 
        public ProductController(IProductRepository repo)
        {
            this.repository = repo;
        }
        public ActionResult List(string category,int page=1)
        {
            ProductsListViewModel model = new ProductsListViewModel()
            {
                Products=repository.Products
                .Where(p=>category==null||p.Category==category)
                .OrderBy(p=>p.ProductId).Skip((page-1)*PageSize).Take(PageSize),
                PagingInfo=new PagingInfo(){
                    CurrentPage=page,
                    ItemsPerPage=PageSize,
                   // TotalItems=repository.Products.Count()
                   TotalItems=category==null? 
                   repository.Products.Count():repository.Products.Where(p=>p.Category==category).Count()
                },
                CurrentCategory=category
            };
            return View(model);
        }
    }
}

OnlineShoppingStore/OnlineShoppingStore.WebUI/Views/Shared/-Admin_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>

</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @{
            var userName = HttpContext.Current.User.Identity.Name;
            if (userName != "")
            {
                //Html.ActionLink(userName, "Logout", "Account");
                <h3>@Html.ActionLink("Online Shopping Store","List","Product")                    
                    <span class="btn-info btn pull-right">
                        @Html.ActionLink(HttpContext.Current.User.Identity.Name + "---Logout", "Logout", "Account")
                    </span>
                </h3>
            }
        }

        @RenderBody()
    </div>
</body>
</html>

OnlineShoppingStore/OnlineShoppingStore.WebUI/Views/Shared/ProductSummary.cshtml
@model OnlineShoppingStore.Domain.Entities.Product

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label-primary">@Model.Price.ToString("c")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart")) 
    {
        <div class="pull-right">
            @Html.HiddenFor(x=>x.ProductId)
            @Html.Hidden("returnUrl",Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart" />
        </div>
    }

    <span class="lead">@Model.Description</span>
</div>

OnlineShoppingStore/OnlineShoppingStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Online Shopping Store</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation" >
        <a class="navbar-brand" href="#">
        <span class="hidden-xs">Online Shopping Store</span>
            <div class="visible-xs">Online</div>
            <div class="visible-xs">Shopping</div>
            <div class="visible-xs">Store</div>
        </a>
        @Html.Action("Summary","Cart")
    </div>
    <div class="row-panel">
        <div id="categories" class="col-lg-3">
            @Html.Action("Menu","Nav")
        </div>
        <div  class="col-lg-7">
            @RenderBody();
        </div>
    </div>
 
</body>
</html>

@*<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>*@